name: Despliegue Automático FTP

on:
  push:
    branches:
      - main # Se ejecutará cada vez que subas cambios a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias y compilar proyecto
        run: |
          npm ci
          npm run build

      - name: Subir archivos al servidor FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # La carpeta que Vite compila
          server-dir: ./ # Cambia esto si debes subirlo a una carpeta específica como /public_html/